import { Inter } from "next/font/google";
import "./globals.css";
import Messages from "./components/Messages";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "carnetbase",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="fixed lg:inset-6 inset-0">
          <section className="grid lg:grid-cols-14 lg:grid-rows-12 grid-rows-18 xl:gap-6 lg:gap-2 h-full">
            <Navbar />
            <Messages />
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
